export default {
  translation: {
    languageSelector: 'Vyberte jazyk',
    welcome: 'Vítejte na OpenChia.io poolu - Oficiální pooling protokol',
    trust: 'Pool, kterému můžete důvěřovat',
    open: 'Veškerý náš software je open source.',
    join: 'připojte se k poolu',
    chat: 'Kontaktujte nás',
    fee: '1% poplatek',
    minPayout: 'Žádná minimální výplata',
    instantPayout: 'Okamžitá výplata',
    transparent: 'Transparentnost',
    feeDesc: 'nízký poplatek s možností doporučení',
    minPayoutDesc: 'Proč čekat na odměnu?',
    instantPayoutDesc: 'Získejte svou odměnu co nejdřív',
    transparentDesc: 'Nemáme co skrývat. Plně funkční explorer a server live logs.',
    chiaPrice: 'XCH cena',
    poolSpace: 'Velikost poolu',
    etw: 'odhadovaný čas',
    blocks: 'Bloky',
    farmers: 'Farmáři',
    netspace: 'Velikost sítě',
    currentEffort: 'Aktuální práce',
    effort: 'Práce',
    sinceLastWin: 'Od poslední výhry',
    rewards: 'Odměny',
    profitability: 'Výdělečnost',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 hod',
    All: 'All',
    friendlyName: 'Přezdívka',
    difficulty: 'Obtížnost',
    joinedAt: 'Připojení:',
    estimatedDailyEarnings: 'Odhadovaný denní zisk',
    points: 'Body',
    utilizationSpace: 'Využitá velikost',
    estimatedSize: 'Odhadovaná velikost',
    partials: 'Partials',
    partial: 'Partial',
    successfulPartials: 'Úspěšné Partials',
    failedPartials: 'Neúspěšné Partials',
    partialPerfomance: 'Partial Výkon',
    harvesterCount: 'Harvestery Počet',
    farmerDetails: 'Detail farmáře',
    payouts: 'Výplaty',
    farmedBlocks: 'Získané bloky',
    scanDesc: 'Nakenujte QR kód z pool login odkazu k aktivaci oznámení.',
    currency: 'Měna',
    currencyDesc: 'Nastavte preferovanou měnu',
    language: 'Jazyk',
    languageDesc: 'Nastavte preferovaný jazyk.',
    rank: 'Rank',
    index: 'Index',
    farmer: 'Farmář',
    date: 'Datum',
    amount: 'množství',
    id: 'ID',
    appearance: 'Vzhled',
    appearanceDesc: 'Světlý, Tmavý',
    general: 'Obecné',
    notifications: 'Oznámení',
    notificationsDesc: 'Partials, Výplaty',
    notification: 'Oznámení',
    notificationDesc: 'Získané bloky',
    home: 'Domů',
    news: 'Zprávy',
    stats: 'Statistiky',
    blocksFound: 'Nalezené bloky',
    darkMode: 'Tmavý vzhled',
    verifyFarm: 'Naskenujte farmu',
    settings: 'Nastavení',
    charts: 'Grafy',
    farms: 'Farmy',
    farmerName: 'Jméno',
    farmerSettings: 'Nastavené farmáře',
    displayName: 'Zobrazené jméno',
    farmName: 'Nastavte jméno',
    totalChiaAccumulated: 'Vyplaceno celkem',
    noPayoutsRecieved: 'Nebyla přijata žádná platba. Tahem dolu obnovte stránku',
    overView: 'Přehled',
    height: 'Výška',
    post: 'Příspěvek',
    giveaway: 'Giveaway',
    drawDate: 'Datum losování',
    ticketIssuance: 'VYDÁNÍ VSTUPENEK',
    ticketsIssued: 'VYDANÉ VSTUPENKY',
    giveawayEveryone:
      'Všichni zemědělci, kteří se účastní našeho fondu, mají automaticky nárok na účast v našem rozdávání!',
    giveawayEveryday:
      'Každý den budou zemědělcům vydány vstupenky na základě jejich odhadované velikosti farmy.',
    ticketDrawing:
      'Losování čísel vstupenek proběhne živě na našem kanálu YouTube a provede se pomocí generátoru náhodných čísel Google. Výhercem se stane farmář s lístkem, který bude nejblíže vylosovanému číslu. Pokud se dva zemědělci budou nacházet ve stejném rozmezí, bude vylosováno další číslo, dokud nebude pouze jeden výherce.',
    ticketAvailabilty:
      'Všechny vydané lístky jsou k dispozici na stránce s podrobnostmi o každém zemědělci.',
    ticketNumber: 'Číslo tipu',
    tickets: 'Lístky',
    ticketsCalculator: 'Kalkulačka vstupene',
    winners: 'Výherci',
    prize: 'Výhra',
    issuedTickets: 'Vydané vstupenky',
    winner: 'Winner',
    chiaPriceChart: 'Chia Price Chart',
  },
};
