export default {
  translation: {
    hello: 'Hello',
    languageSelector: 'Select Your Language',
    welcome: 'Welcome to OpenChia.io Official Pool Protocol',
    trust: 'A pool you can trust.',
    open: 'All our software is open source.',
    join: 'Join our Pool',
    chat: 'Chat with us',
    fee: '1% Fee',
    minPayout: 'No Minimum payout',
    instantPayout: 'Instant payout',
    transparent: 'Transparent',
    feeDesc: 'Low fee with referral option.',
    minPayoutDesc: 'Why wait to get your rewards?',
    instantPayoutDesc: 'Get your reward as soon as possible.',
    transparentDesc: 'We have nothing to hide. Full blown explorer and live logs.',
    chiaPrice: 'Chia Price',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Blocks',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Current Effort',
    effort: 'Effort',
    sinceLastWin: 'Since Last Win',
    rewards: 'Rewards',
    profitability: 'Profitabilty',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 Hours',
    All: 'All',
    friendlyName: 'Friendly Name',
    difficulty: 'Difficulty',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Esimated Daily Earnings',
    points: 'Points',
    utilizationSpace: 'Utilization Space',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Successful Partials',
    failedPartials: 'Failed Partials',
    performance: 'Performance',
    harvesters: 'Harvesters',
    count: 'count',
    farmerDetails: 'Farmer Details',
    payouts: 'Payouts',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Scan QR code from pool login link to receive notifications.',
    currency: 'Currency',
    currencyDesc: 'Set preferred currency.',
    language: 'Language',
    languageDesc: 'Set preferred language.',
    rank: 'Rank',
    index: 'Index',
    farmer: 'Farmer',
    date: 'Date',
    amount: 'Amount',
    id: 'ID',
    appearance: 'Appearance',
    appearanceDesc: 'Light, Dark',
    general: 'General',
    notifications: 'Notifications',
    notificationsDesc: 'Partials, Payouts',
    notification: 'Notification',
    notificationDesc: 'Blocks Won',
    home: 'Home',
    news: 'News',
    stats: 'Stats',
    blocksFound: 'Blocks Found',
    darkMode: 'Dark Mode',
    verifyFarm: 'Verify Farm',
    settings: 'Settings',
    charts: 'Charts',
    farms: 'Farms',
    farmerName: 'Name',
    farmerSettings: 'Farmer Settings',
    displayName: 'Display Name',
    farmName: 'Update Name',
    totalChiaAccumulated: 'Total Paid',
    noPayoutsRecieved: 'No payouts received yet. Pull down to refresh.',
    overView: 'Overview',
  },
};
