export default {
  translation: {
    languageSelector: 'Select Your Language',
    welcome: 'Welcome to OpenChia.io Official Pool Protocol',
    trust: 'A pool you can trust.',
    open: 'All our software is open source.',
    join: 'Join our Pool',
    chat: 'Chat with us',
    fee: '1% Fee',
    minPayout: 'No Minimum payout',
    instantPayout: 'Instant payout',
    transparent: 'Transparent',
    feeDesc: 'Low fee with referral option.',
    minPayoutDesc: 'Why wait to get your rewards?',
    instantPayoutDesc: 'Get your reward as soon as possible.',
    transparentDesc: 'We have nothing to hide. Full blown explorer and live logs.',
    chiaPrice: 'Chia Price',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Blocks',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Current Effort',
    effort: 'Effort',
    sinceLastWin: 'Since Last Win',
    rewards: 'Rewards',
    profitability: 'Profitabilty',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 Hours',
    All: 'All',
    friendlyName: 'Friendly Name',
    difficulty: 'Difficulty',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Esimated Daily Earnings',
    points: 'Points',
    utilizationSpace: 'Utilization Space',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Successful Partials',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Partial Performance',
    harvesterCount: 'Harvesters Count',
    farmerDetails: 'Farmer Details',
    payouts: 'Payouts',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Scan QR code from pool login link to receive notifications.',
    currency: 'Currency',
    currencyDesc: 'Set preferred currency.',
    language: 'Language',
    languageDesc: 'Set preferred language.',
    rank: 'Rank',
    index: 'Index',
    farmer: 'Farmer',
    date: 'Date',
    amount: 'Amount',
    id: 'ID',
    appearance: 'Appearance',
    appearanceDesc: 'Light, Dark',
    general: 'General',
    notifications: 'Notifications',
    notificationsDesc: 'Offline, Blocks',
    notification: 'Notification',
    notificationDesc: 'Blocks Won',
    home: 'Home',
    news: 'News',
    stats: 'Stats',
    blocksFound: 'Blocks Found',
    darkMode: 'Dark Mode',
    verifyFarm: 'Verify Farm',
    settings: 'Settings',
    charts: 'Charts',
    farms: 'Farms',
    farmerName: 'Name',
    farmerSettings: 'Farmer Settings',
    displayName: 'Display Name',
    farmName: 'Update Name',
    totalChiaAccumulated: 'Total Paid',
    noPayoutsRecieved: 'No payouts received yet. Pull down to refresh.',
    overView: 'Overview',
    height: 'Height',
    post: 'Post',
    giveaway: 'Giveaway',
    drawDate: 'Draw Date',
    ticketIssuance: 'Tickets Issuance',
    ticketsIssued: 'Tickets Issued',
    giveawayEveryone:
      'All farmers participating in our pool are automatically eligible in our giveaway!',
    giveawayEveryday:
      'Every day farmers will be issued tickets based on their estimated farm size.',
    ticketDrawing:
      'Draw of the ticket number will happen live in our YouTube channel and done using Google random number generator. The winner will be the farmer with the ticket closest to the number draw. If two farmers are within the same range another number will be drawed until there is only one winner.',
    ticketAvailabilty: 'All tickets issued are made available in each farmer detail page.',
    ticketNumber: 'Ticket Number',
    tickets: 'Giveaway Tickets',
    ticketsCalculator: 'Tickets Calculator',
    winners: 'Winners',
    prize: 'Prize',
    issuedTickets: 'Issued Tickets',
    winner: 'Winner',
    chiaPriceChart: 'Chia Price Chart',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'No Partials Passed For 1h',
    farmerBlockNotification: 'Block Won By Farmer',
    farmerNotifications: 'Farm Notifications',
    activeFarms: 'Farmers',
    activeFarmsDesc: 'Show Only Active Farmers',
    groupName: 'Group Title',
  },
};
