export default {
  translation: {
    languageSelector: 'Seleccione su idioma',
    welcome: 'Bienvenido al protocolo oficial de la piscina de OpenChia.io',
    trust: 'Un pool en el que puedes confiar',
    open: 'Todo nuestro software es de código abierto',
    join: 'Únete a nuestra quiniela',
    chat: 'Chatea con nosotros',
    fee: 'Cuota del 1%',
    minPayout: 'Sin pago mínimo',
    instantPayout: 'Pago instantáneo',
    transparent: 'Transparente',
    feeDesc: 'Baja comisión con opción de recomendación',
    minPayoutDesc: '¿Por qué esperar para obtener sus recompensas?',
    instantPayoutDesc: 'Obtenga su recompensa lo antes posible',
    transparentDesc: 'No tenemos nada que ocultar. Explorador completo y registros en vivo',
    chiaPrice: 'Precio de la chía',
    poolSpace: 'Espacio de la piscina',
    etw: 'etw',
    blocks: 'Bloques',
    farmers: 'Agricultores',
    netspace: 'Netspace',
    currentEffort: 'Esfuerzo actual',
    effort: 'Esfuerzo',
    sinceLastWin: 'Desde la última victoria',
    rewards: 'Recompensas',
    profitability: 'Rentabilidad',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 horas',
    All: 'Todos',
    friendlyName: 'Nombre amigable',
    difficulty: 'Dificultad',
    joinedAt: 'Ingresado en',
    estimatedDailyEarnings: 'Ganancias diarias estimadas',
    points: 'Puntos',
    utilizationSpace: 'Espacio de utilización',
    estimatedSize: 'Espacio estimado',
    partials: 'Parciales',
    partial: 'Parcial',
    successfulPartials: 'Parciales exitosos',
    failedPartials: 'Parciales fallidos',
    partialPerfomance: 'Rendimiento parcial',
    harvesterCount: 'Recuento de cosechadoras',
    farmerDetails: 'Detalles del agricultor',
    payouts: 'Pagos',
    farmedBlocks: 'Bloques cultivados',
    scanDesc:
      'Escanear el código QR del enlace de inicio de sesión de la piscina para recibir notificaciones',
    currency: 'Moneda',
    currencyDesc: 'Establecer la moneda preferida',
    language: 'Idioma',
    languageDesc: 'Establecer el idioma preferido.',
    rank: 'Rango',
    index: 'Índice',
    farmer: 'Agricultor',
    date: 'Fecha',
    amount: 'Importe',
    id: 'ID',
    appearance: 'Aspecto',
    appearanceDesc: 'Claro, oscuro',
    general: 'General',
    notifications: 'Notificaciones',
    notificationsDesc: 'Parciales, Pagos',
    notification: 'Notificación',
    notificationDesc: 'Bloques ganados',
    home: 'Inicio',
    news: 'Noticias',
    stats: 'Estadísticas',
    blocksFound: 'Bloques encontrados',
    darkMode: 'Modo oscuro',
    verifyFarm: 'Verificar granja',
    settings: 'Ajustes',
    charts: 'Gráficos',
    farms: 'Granjas',
    farmerName: 'Nombre',
    farmerSettings: 'Ajustes del agricultor',
    displayName: 'Nombre de la pantalla',
    farmName: 'Actualizar nombre',
    totalChiaAccumulated: 'Total pagado',
    noPayoutsRecieved: 'No se han recibido pagos todavía. Tire hacia abajo para actualizar',
    overView: 'Resumen',
  },
};
