export default {
  translation: {
    languageSelector: 'Seleccione su idioma',
    welcome: 'Bienvenido a la pool OpenChia.io de protocolo oficial',
    trust: 'Una pool en la que puedes confiar',
    open: 'Todo nuestro software es de código abierto',
    join: 'Únete a nuestra pool',
    chat: 'Chatea con nosotros',
    fee: 'Cuota del 1%',
    minPayout: 'Sin pago mínimo',
    instantPayout: 'Pago instantáneo',
    transparent: 'Transparente',
    feeDesc: 'Comisión baja con opción de recomendados',
    minPayoutDesc: '¿Por qué esperar para obtener sus recompensas?',
    instantPayoutDesc: 'Obtenga su recompensa lo antes posible',
    transparentDesc: 'No tenemos nada que ocultar. Explorador completo y registros en tiempo real',
    chiaPrice: 'Precio del chía',
    poolSpace: 'Espacio de la pool',
    etw: 'etw',
    blocks: 'Bloques',
    farmers: 'Agricultores',
    netspace: 'Netspace',
    currentEffort: 'Esfuerzo actual',
    effort: 'Esfuerzo',
    sinceLastWin: 'Desde el último bloque ganado',
    rewards: 'Recompensas',
    profitability: 'Rentabilidad',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 horas',
    All: 'Todos',
    friendlyName: 'Nombre amigable',
    difficulty: 'Dificultad',
    joinedAt: 'Ingresado en',
    estimatedDailyEarnings: 'Ganancias diarias estimadas',
    points: 'Puntos',
    utilizationSpace: 'Espacio de utilización',
    estimatedSize: 'Espacio estimado',
    partials: 'Parciales',
    partial: 'Parcial',
    successfulPartials: 'Parciales exitosos',
    failedPartials: 'Parciales fallidos',
    partialPerfomance: 'Rendimiento parcial',
    harvesterCount: 'Recuento de cosechadoras',
    farmerDetails: 'Detalles del farmer',
    payouts: 'Pagos',
    farmedBlocks: 'Bloques cultivados',
    scanDesc:
      'Escanea el código QR del enlace de de inicio de sesión a la pool para recibir notificaciones',
    currency: 'Moneda',
    currencyDesc: 'Establecer la moneda preferida',
    language: 'Idioma',
    languageDesc: 'Establecer el idioma preferido.',
    rank: 'Rango',
    index: 'Índice',
    farmer: 'Agricultor',
    date: 'Fecha',
    amount: 'Importe',
    id: 'ID',
    appearance: 'Aspecto',
    appearanceDesc: 'Claro, Oscuro',
    general: 'General',
    notifications: 'Notificaciones',
    notificationsDesc: 'Parciales, Pagos',
    notification: 'Notificación',
    notificationDesc: 'Bloques ganados',
    home: 'Inicio',
    news: 'Noticias',
    stats: 'Estadísticas',
    blocksFound: 'Bloques encontrados',
    darkMode: 'Modo oscuro',
    verifyFarm: 'Verificar granja',
    settings: 'Ajustes',
    charts: 'Gráficas',
    farms: 'Granjas',
    farmerName: 'Nombre',
    farmerSettings: 'Ajustes del farmer',
    displayName: 'Nombre a mostrar',
    farmName: 'Actualizar nombre',
    totalChiaAccumulated: 'Total pagado',
    noPayoutsRecieved: 'No se han recibido pagos todavía. Deslice hacia abajo para actualizar',
    overView: 'Resumen',
    height: 'Altura',
    post: 'Post',
    giveaway: 'Sorteo',
    drawDate: 'Fecha del sorteo',
    ticketIssuance: 'EMISIÓN DE BOLETOS',
    ticketsIssued: 'EMISIÓN DE BOLETOS',
    giveawayEveryone:
      'Todos los granjeros que participen en nuestra pool son automáticamente elegibles en nuestro sorteo!',
    giveawayEveryday:
      'Cada día se emitirán boletos a los granjeros en función del tamaño estimado de su granja.',
    ticketDrawing:
      'El sorteo del boleto ganador se realizará en directo en nuestro canal de YouTube y se hará mediante un generador de números aleatorios de Google. El ganador será el granjero con el boleto más cercano al número premiado. Si dos farmers están dentro del mismo rango se sorteará otro número hasta que haya un solo ganador.',
    ticketAvailabilty:
      'Todos los boletos emitidos están disponibles en la página de detalles de cada farmer',
    ticketNumber: 'Número de boletos',
    tickets: 'Boletos',
    ticketsCalculator: 'Calculadora de boletos',
    winners: 'Ganadores',
    prize: 'Premio',
    issuedTickets: 'Boletos emitidos',
    winner: 'Ganador',
    chiaPriceChart: 'Tabla de precios de Chia',
    farmerOffline: 'Desconectado',
    farmerOfflineNotification: 'No hay parciales válidos en 1h',
    farmerBlockNotification: 'Bloque ganado por granjero',
    farmerNotifications: 'Notificaciones de granjero',
  },
};
