export default {
  translation: {
    hello: 'Bonjour',
    languageSelector: 'Sélectionnez votre langue',
    welcome: 'Bienvenue sur OpenChia.io - Protocol de pooling officiel',
    trust: 'Un pool sur lequel vous pouvez compter.',
    open: 'Tous nos logiciels sont Open Source.',
    join: 'Joindre notre Pool',
    chat: 'Communiquer avec nous',
    fee: 'Frais de 1%',
    minPayout: 'Aucun paiement minimal',
    instantPayout: 'Paiement instantanné',
    transparent: 'Transparent',
    feeDesc: 'Frais moindres lorsque vous référez quelqu`un.',
    minPayoutDesc: 'Pourquoi attendre pour avant de recevoir votre paiement?',
    instantPayoutDesc: 'Recevez vos récompenses dès que possible.',
    transparentDesc:
      'Nous n`avons rien à cacher. Tout est ouvert, vous avez même accès aux logs en temps réel.',
    chiaPrice: 'Prix du Chia',
    poolSpace: 'Grosseur du Pool',
    etw: 'etw',
    blocks: 'Blocs',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Effort courant',
    effort: 'Effort',
    sinceLastWin: 'Depuis le dernier gain',
    rewards: 'Récompenses',
    profitability: 'Profitabilité',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2j',
    '3d': '3j',
    '7d': '7j',
    '30d': '30j',
    '90d': '90j',
    '24Hours': '24 Heures',
    All: 'Tout',
    friendlyName: 'Nom courant',
    difficulty: 'Difficulté',
    joinedAt: 'Membre depuis',
    estimatedDailyEarnings: 'Gains journaliers estimés',
    points: 'Points',
    utilizationSpace: 'Pourcentage total',
    estimatedSize: 'Espace estimée',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Partials validés',
    failedPartials: 'Partials Échoués',
    performance: 'Performance',
    harvesters: 'Harvesters',
    count: 'nombre de',
    farmerDetails: 'Détails du Farmer',
    payouts: 'Paiements',
    farmedBlocks: 'Blocs trouvés',
    scanDesc:
      'Scannez votre code QR à partir du lien de connexion personnel pour recevoir les notifications.',
    currency: 'Devise',
    currencyDesc: 'Définir la devise préférée.',
    language: 'Langue',
    languageDesc: 'Définir la langue préférée.',
    rank: 'Position',
    index: 'Indexe',
    farmer: 'Farmer',
    date: 'Date',
    amount: 'Montant',
    id: 'ID',
    appearance: 'Apparence',
    appearanceDesc: 'Jour, Nuit',
    general: 'Général',
    notifications: 'Notifications',
    notificationsDesc: 'Partials, Payouts',
    notification: 'Notification',
    notificationDesc: 'Blocks Won',
    home: 'Accueil',
    news: 'Nouvelles',
    stats: 'Stats',
    blocksFound: 'Blocs Trouvés',
    darkMode: 'Mode nuit',
    verifyFarm: 'Vérifier la Farm',
    settings: 'Paramêtres',
    charts: 'Graphiques',
    farms: 'Farms',
    farmerName: 'Name',
    farmerSettings: 'Farmer Settings',
    displayName: 'Display Name',
    farmName: 'Name',
    totalChiaAccumulated: 'Total Paid',
    noPayoutsRecieved: 'No payouts received yet. Pull down to refresh.',
    overView: 'Overview',
  },
};
