export default {
  translation: {
    languageSelector: 'Válassza ki a nyelvet',
    welcome: 'Üdvözöljük az OpenChia.io hivatalos pool protokollján',
    trust: 'Egy medence, amelyben megbízhatsz.',
    open: 'Minden szoftverünk nyílt forráskódú.',
    join: 'Csatlakozz a poolunkhoz',
    chat: 'Csevegj velünk',
    fee: '1%-os díj',
    minPayout: 'Nincs minimális kifizetés',
    instantPayout: 'Azonnali kifizetés',
    transparent: 'Átlátható',
    feeDesc: 'Alacsony díj az ajánlási lehetőséggel.',
    minPayoutDesc: 'Miért várjon a jutalmakra?',
    instantPayoutDesc: 'A lehető leghamarabb kapja meg jutalmát.',
    transparentDesc: 'Nincs semmi rejtegetnivalónk. Teljes körű explorer és élő naplózás.',
    chiaPrice: 'Chia ár',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Blocks',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Jelenlegi erőfeszítés',
    effort: 'Erőfeszítés',
    sinceLastWin: 'Utolsó győzelem óta',
    rewards: 'Jutalmak',
    profitability: 'Nyereségesség',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 óra',
    All: 'All',
    friendlyName: 'Barátságos név',
    difficulty: 'Nehézség',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Előrejelzett napi kereset',
    points: 'Pontok',
    utilizationSpace: 'Felhasználási hely',
    estimatedSize: 'Esimated Space',
    partials: 'Részösszegek',
    partial: 'részleges',
    successfulPartials: 'Sikeres részlegesek',
    failedPartials: 'Sikertelen részlegesek',
    partialPerfomance: 'Részleges teljesítmény',
    harvesterCount: 'Harvesters Count',
    farmerDetails: 'Farmer részletek',
    payouts: 'Kifizetések',
    farmedBlocks: 'Megművelt blokkok',
    scanDesc:
      'Szkennelje be a QR-kódot a medence bejelentkezési linkről az értesítések fogadásához.',
    currency: 'Valuta',
    currencyDesc: 'Állítsa be a kívánt pénznemet.',
    language: 'Nyelv',
    languageDesc: 'Set preferred language.',
    rank: 'Rang',
    index: 'Index',
    farmer: 'Farmer',
    date: 'Dátum',
    amount: 'Amount',
    id: 'ID',
    appearance: 'Megjelenés',
    appearanceDesc: 'Világos, sötét',
    general: 'Általános',
    notifications: 'Értesítések',
    notificationsDesc: 'Részletfizetések, kifizetések',
    notification: 'Értesítés',
    notificationDesc: 'Nyert blokkok',
    home: 'Kezdőlap',
    news: 'Hírek',
    stats: 'Statisztikák',
    blocksFound: 'Megtalált blokkok',
    darkMode: 'Sötét üzemmód',
    verifyFarm: 'Verify Farm',
    settings: 'Beállítások',
    charts: 'Diagramok',
    farms: 'Farmok',
    farmerName: 'Név',
    farmerSettings: 'Farmer beállítások',
    displayName: 'Display Name',
    farmName: 'Név frissítése',
    totalChiaAccumulated: 'Összesen fizetett',
    noPayoutsRecieved: 'Még nem érkezett kifizetés. Húzza le a frissítéshez.',
    overView: 'Áttekintés',
    height: 'Magasság',
    post: 'Sorsolás dátuma',
    giveaway: 'Ajándék',
    drawDate: 'Sorsolás dátuma',
    ticketIssuance: 'JEGYEK KIADÁSA',
    ticketsIssued: 'KIADOTT JEGYEK',
    giveawayEveryone:
      'Minden, a totónkban részt vevő gazdálkodó automatikusan jogosult a nyereményjátékban való részvételre!',
    giveawayEveryday: 'A gazdák minden nap a becsült gazdaságuk mérete alapján kapnak jegyeket.',
    ticketDrawing:
      'A jegyek számának kisorsolása élőben történik a YouTube csatornánkon, és a Google véletlenszám-generátor segítségével történik. A nyertes az a gazda lesz, akinek a szelvénye a legközelebb van a sorsoláshoz. Ha két gazda azonos tartományon belül van, újabb számot húzunk, amíg csak egy nyertes nem lesz.',
    ticketAvailabilty:
      'Az összes kiadott szelvény elérhetővé válik az egyes gazdálkodók adatlapján.',
    ticketNumber: 'Jegyszám',
    tickets: 'Jegyek',
    ticketsCalculator: 'Jegyek kalkulátor',
    winners: 'Nyertesek',
    prize: 'Díj',
    issuedTickets: 'Kiadott jegyek',
    winner: 'Nyertes',
    chiaPriceChart: 'Chia árdiagram',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'Nincs részleges átadott 1 órán át',
    farmerBlockNotification: 'Gazdálkodó által megnyert blokk',
    farmerNotifications: 'Mezőgazdasági értesítések',
    groupName: 'Group Title',
  },
};
