export default {
  translation: {
    languageSelector: 'Válassza ki a nyelvet',
    welcome: 'Üdvözöljük az OpenChia.io hivatalos pool protokollján',
    trust: 'Egy medence, amelyben megbízhatsz.',
    open: 'Minden szoftverünk nyílt forráskódú.',
    join: 'Csatlakozz a poolunkhoz',
    chat: 'Csevegj velünk',
    fee: '1%-os díj',
    minPayout: 'Nincs minimális kifizetés',
    instantPayout: 'Azonnali kifizetés',
    transparent: 'Átlátható',
    feeDesc: 'Alacsony díj az ajánlási lehetőséggel.',
    minPayoutDesc: 'Miért várjon a jutalmakra?',
    instantPayoutDesc: 'A lehető leghamarabb kapja meg jutalmát.',
    transparentDesc: 'Nincs semmi rejtegetnivalónk. Teljes körű explorer és élő naplózás.',
    chiaPrice: 'Chia ár',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Blocks',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Jelenlegi erőfeszítés',
    effort: 'Erőfeszítés',
    sinceLastWin: 'Utolsó győzelem óta',
    rewards: 'Jutalmak',
    profitability: 'Nyereségesség',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 óra',
    All: 'All',
    friendlyName: 'Barátságos név',
    difficulty: 'Nehézség',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Előrejelzett napi kereset',
    points: 'Pontok',
    utilizationSpace: 'Felhasználási hely',
    estimatedSize: 'Esimated Space',
    partials: 'Részösszegek',
    partial: 'részleges',
    successfulPartials: 'Sikeres részlegesek',
    failedPartials: 'Sikertelen részlegesek',
    partialPerfomance: 'Részleges teljesítmény',
    harvesterCount: 'Harvesters Count',
    farmerDetails: 'Farmer részletek',
    payouts: 'Kifizetések',
    farmedBlocks: 'Megművelt blokkok',
    scanDesc:
      'Szkennelje be a QR-kódot a medence bejelentkezési linkről az értesítések fogadásához.',
    currency: 'Valuta',
    currencyDesc: 'Állítsa be a kívánt pénznemet.',
    language: 'Nyelv',
    languageDesc: 'Set preferred language.',
    rank: 'Rang',
    index: 'Index',
    farmer: 'Farmer',
    date: 'Dátum',
    amount: 'Amount',
    id: 'ID',
    appearance: 'Megjelenés',
    appearanceDesc: 'Világos, sötét',
    general: 'Általános',
    notifications: 'Értesítések',
    notificationsDesc: 'Részletfizetések, kifizetések',
    notification: 'Értesítés',
    notificationDesc: 'Nyert blokkok',
    home: 'Kezdőlap',
    news: 'Hírek',
    stats: 'Statisztikák',
    blocksFound: 'Megtalált blokkok',
    darkMode: 'Sötét üzemmód',
    verifyFarm: 'Verify Farm',
    settings: 'Beállítások',
    charts: 'Diagramok',
    farms: 'Farmok',
    farmerName: 'Név',
    farmerSettings: 'Farmer beállítások',
    displayName: 'Display Name',
    farmName: 'Név frissítése',
    totalChiaAccumulated: 'Összesen fizetett',
    noPayoutsRecieved: 'Még nem érkezett kifizetés. Húzza le a frissítéshez.',
    overView: 'Áttekintés',
    height: 'Magasság',
    post: 'Post',
    giveaway: 'Giveaway',
    drawDate: 'Draw Date',
    ticketIssuance: 'TICKETS ISSUANCE',
    ticketsIssued: 'TICKETS ISSUED',
    giveawayEveryone:
      'All farmers participating in our pool are automatically eligible in our giveaway!',
    giveawayEveryday:
      'Every day farmers will be issued tickets based on their estimated farm size.',
    ticketDrawing:
      'Draw of the ticket number will happen live in our YouTube channel and done using Google random number generator. The winner will be the farmer with the ticket closest to the number draw. If two farmers are within the same range another number will be drawed until there is only one winner.',
    ticketAvailabilty: 'All tickets issued are made available in each farmer detail page.',
    ticketNumber: 'Ticket Number',
    tickets: 'Tickets',
    ticketsCalculator: 'Tickets Calculator',
    winners: 'Winners',
    prize: 'Prize',
    issuedTickets: 'Issued Tickets',
    winner: 'Winner',
    chiaPriceChart: 'Chia Price Chart',
  },
};
