export default {
  translation: {
    languageSelector: 'Selecteer je taal',
    welcome: 'Welkom bij het offciële Openchia Pool Protocol',
    trust: 'Een pool die je kan vertrouwen',
    open: 'Al onze software is open source.',
    join: 'Voeg je bij onze Pool',
    chat: 'Chat met ons',
    fee: '1% Fee',
    minPayout: 'Geen minimale uitbetaling',
    instantPayout: 'Meteen uitbetaald',
    transparent: 'Transparant',
    feeDesc: 'Lage kosten met vriend doorverwijzingssysteem.',
    minPayoutDesc: 'Waarom wachten op je uitbetaling?',
    instantPayoutDesc: 'Krijg je opbrengsten meteen als ze beschikbaar zijn.',
    transparentDesc: 'We hebben niets te verbergen. Volledig open boek explorer en logs.',
    chiaPrice: 'Chia Prijs',
    poolSpace: 'Pool Grootte',
    etw: 'Geschatte tijd tot volgende block',
    blocks: 'Blocks',
    farmers: 'Farmers',
    netspace: 'Netwerk grootte',
    currentEffort: 'Huidige Effort',
    effort: 'Effort',
    sinceLastWin: 'Sinds laatst gewonnen block',
    rewards: 'Uitbetalingen',
    profitability: 'Winstgevendheid',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24hours': '24 uur',
    All: 'Alle',
    friendlyName: 'Bijnaam',
    difficulty: 'Moeilijkheidsgraad',
    joinedAt: 'Aangesloten sinds',
    estimatedDailyEarnings: 'Geschatte dagelijkse inkomsten',
    points: 'Punten',
    utilizationSpace: 'Gebruikte opslagruimte',
    estimatedSize: 'Geschatte opslagruimte',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Successvolle Partials',
    failedPartials: 'Gefaalde Partials',
    partialPerfomance: 'Prestaties van Partials',
    harvesterCount: 'Aantal Harvesters',
    farmerDetails: 'Gedetaileerde info van Farmer',
    payouts: 'Uitbetalingen',
    farmedBlocks: 'Gewonnen Blocks',
    scanDesc: 'Scan QR code van de pool login link voor notificaties te activeren.',
    currency: 'valuta',
    currencyDesc: 'Selecteer valuta.',
    language: 'Taal',
    languageDesc: 'Voorkeurstaal.',
    rank: 'Rang',
    index: 'Index',
    farmer: 'Farmer',
    date: 'Datum',
    amount: 'Hoeveelheid',
    id: 'ID',
    appearance: 'Uiterlijk',
    appearanceDesc: 'Lichte versie, Donkere versie',
    general: 'Algemeen',
    notifications: 'Notificaties',
    notificationsDesc: 'Partials, Uitbetalingen',
    notification: 'Notificaties',
    notificationDesc: 'Gewonnen Blocks',
    home: 'Startpagina',
    news: 'Nieuws',
    stats: 'Statistieken',
    blocksFound: 'Gewonnen blocks',
    darkMode: 'Donkere modus',
    verifyFarm: 'Verifiëer Farm',
    settings: 'Instellingen',
    charts: 'Kaarten',
    farms: 'Farms',
    farmerName: 'Naam',
    farmerSettings: 'Farmer instellingen',
    displayName: 'Gebruikersnaam',
    farmName: 'Update gebruikersnaam',
    totalChiaAccumulated: 'Totaal uitbetaald',
    noPayoutsRecieved: 'Nog geen uitbetalingen ontvangen. refresh om opnieuw te laden.',
    overView: 'Overzicht',
    height: 'Hoogte',
    post: 'Post',
    giveaway: 'Weggeefactie',
    drawDate: 'Datum van de loting',
    ticketIssuance: 'Uitgifte van Tickets',
    ticketsIssued: 'Toegekende Tickets',
    giveawayEveryone:
      'Alle farmers die aangesloten zijn bij onze pool doen automatisch mee aan de weggeefactie!',
    giveawayEveryday:
      'Elke dag krijgen alle farmers automatisch tickets toegewezen aan de hand van farm grootte in de pool.',
    ticketDrawing:
      'Ticket nummer zal live via ons Youtube kanaal getrokken worden door de Google Random Number Generator. Het ticket met het nummer dichtst bij het getrokken nummer wint. Indien meerdere tickets even dicht bij het gewonnen nummer uitkomen zal een nieuw nummer getrokken worden tot er maar één winnaar is.',
    ticketAvailabilty:
      'Alle toegekende tickets zijn voor elke farmer beschibaar via de ticketpagina',
    ticketNumber: 'Ticket Nummer',
    tickets: 'Toegekende Tickets',
    ticketsCalculator: 'Berekening van Tickets',
    winners: 'Winnaars',
    prize: 'Prijs',
    issuedTickets: 'Toegekende Tickets',
    winner: 'Winnaar',
    chiaPriceChart: 'Chia Prijs overzicht',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'Geen Partials gepasseerd voor 1 uur',
    farmerBlockNotification: 'Blok gewonnen door boer',
    farmerNotifications: 'Kennisgevingen van Farm',
  },
};
