export default {
  translation: {
    languageSelector: 'Wybierz swój język',
    welcome: 'Witamy w oficjalnym protokole puli OpenChia.io',
    trust: 'Basen, któremu możesz zaufać.',
    open: 'Całe nasze oprogramowanie jest open source',
    join: 'Dołącz do naszego basenu',
    chat: 'Czat z nami',
    fee: '1% Fee',
    minPayout: 'Brak minimalnej wypłaty',
    instantPayout: 'Natychmiastowa wypłata',
    transparent: 'Przejrzystość',
    feeDesc: 'Niska opłata z opcją polecania',
    minPayoutDesc: 'Po co czekać z otrzymaniem nagrody?',
    instantPayoutDesc: 'Otrzymaj swoją nagrodę tak szybko jak to możliwe',
    transparentDesc: 'Nie mamy nic do ukrycia. Pełen eksplorator i logi na żywo.',
    chiaPrice: 'Cena Chia',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Bloki',
    farmers: 'Farmerzy',
    netspace: 'Netspace',
    currentEffort: 'bieżący wysiłek',
    effort: 'Effort',
    sinceLastWin: 'Od ostatniej wygranej',
    rewards: 'Nagrody',
    profitability: 'Rentowność',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 godziny',
    All: 'Wszystkie',
    friendlyName: 'Przyjazna nazwa',
    difficulty: 'Trudność',
    joinedAt: 'Połączony przy',
    estimatedDailyEarnings: 'Szacowane Dzienne Zarobki',
    points: 'Punkty',
    utilizationSpace: 'Przestrzeń użytkowa',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'częściowe',
    successfulPartials: 'Successful Partials',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Partial Performance',
    harvesterCount: 'Harvesters Count',
    farmerDetails: 'Szczegóły dotyczące rolników',
    payouts: 'Wypłaty',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Zeskanuj kod QR z linku logowania do puli, aby otrzymywać powiadomienia.',
    currency: 'Waluta',
    currencyDesc: 'Ustaw preferowaną walutę',
    language: 'Język',
    languageDesc: 'Ustaw preferowany język.',
    rank: 'Rank',
    index: 'Indeks',
    farmer: 'Rolnik',
    date: 'Data',
    amount: 'Kwota',
    id: 'ID',
    appearance: 'Wygląd',
    appearanceDesc: 'Jasny, Ciemny',
    general: 'Ogólne',
    notifications: 'Powiadomienia',
    notificationsDesc: 'Części, Wypłaty',
    notification: 'Powiadomienia',
    notificationDesc: 'Wygrane bloki',
    home: 'Dom',
    news: 'Wiadomości',
    stats: 'Statystyki',
    blocksFound: 'Znalezione bloki',
    darkMode: 'Tryb ciemny',
    verifyFarm: 'Zweryfikuj farmę',
    settings: 'Ustawienia',
    charts: 'Charts',
    farms: 'Gospodarstwa',
    farmerName: 'Nazwa',
    farmerSettings: 'Ustawienia gospodarstwa',
    displayName: 'Nazwa wyświetlana',
    farmName: 'Nazwa aktualizacji',
    totalChiaAccumulated: 'Razem wypłacone',
    noPayoutsRecieved: 'Nie otrzymano jeszcze żadnych wypłat. Pociągnij w dół, aby odświeżyć.',
    overView: 'Przegląd',
    height: 'Wysokość',
    post: 'Post',
    giveaway: 'Giveaway',
    drawDate: 'Data losowania',
    ticketIssuance: 'WYSTAWIENIE BILETÓW',
    ticketsIssued: 'BILETY WYDANE',
    giveawayEveryone:
      'Wszyscy rolnicy uczestniczący w naszej puli automatycznie kwalifikują się do udziału w naszym losowaniu!',
    giveawayEveryday:
      'Każdego dnia rolnicy będą otrzymywać bilety na podstawie szacowanej wielkości ich gospodarstwa.',
    ticketDrawing:
      'Losowanie numerów biletów odbędzie się na żywo na naszym kanale YouTube i zostanie przeprowadzone przy użyciu generatora liczb losowych Google. Zwycięzcą zostanie rolnik, którego bilet będzie najbliższy wylosowanemu numerowi. Jeśli dwóch rolników znajdzie się w tym samym przedziale, wylosowany zostanie kolejny numer, aż do momentu, gdy będzie tylko jeden zwycięzca.',
    ticketAvailabilty: 'All tickets issued are made available in each farmer detail page.',
    ticketNumber: 'Ticket Number',
    tickets: 'Bilety',
    ticketsCalculator: 'Kalkulator biletów',
    winners: 'Zwycięzcy',
    prize: 'Nagroda',
    issuedTickets: 'Wydane bilety',
    winner: 'Zwycięzca',
    chiaPriceChart: 'Wykres ceny Chia',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'No Partials Passed For 1h',
    farmerBlockNotification: 'Block Won By Farmer',
    farmerNotifications: 'Farm Notifications',
  },
};
