export default {
  translation: {
    languageSelector: 'Wybierz swój język',
    welcome: 'Witamy w oficjalnym protokole puli OpenChia.io',
    trust: 'Basen, któremu możesz zaufać.',
    open: 'Całe nasze oprogramowanie jest open source',
    join: 'Dołącz do naszego basenu',
    chat: 'Czat z nami',
    fee: '1% Fee',
    minPayout: 'Brak minimalnej wypłaty',
    instantPayout: 'Natychmiastowa wypłata',
    transparent: 'Przejrzystość',
    feeDesc: 'Niska opłata z opcją polecania',
    minPayoutDesc: 'Po co czekać z otrzymaniem nagrody?',
    instantPayoutDesc: 'Otrzymaj swoją nagrodę tak szybko jak to możliwe',
    transparentDesc: 'Nie mamy nic do ukrycia. Pełen eksplorator i logi na żywo.',
    chiaPrice: 'Cena Chia',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Bloki',
    farmers: 'Farmerzy',
    netspace: 'Netspace',
    currentEffort: 'bieżący wysiłek',
    effort: 'Effort',
    sinceLastWin: 'Od ostatniej wygranej',
    rewards: 'Nagrody',
    profitability: 'Rentowność',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 godziny',
    All: 'Wszystkie',
    friendlyName: 'Przyjazna nazwa',
    difficulty: 'Trudność',
    joinedAt: 'Połączony przy',
    estimatedDailyEarnings: 'Szacowane Dzienne Zarobki',
    points: 'Punkty',
    utilizationSpace: 'Przestrzeń użytkowa',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'częściowe',
    successfulPartials: 'Successful Partials',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Partial Performance',
    harvesterCount: 'Harvesters Count',
    farmerDetails: 'Szczegóły dotyczące rolników',
    payouts: 'Wypłaty',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Zeskanuj kod QR z linku logowania do puli, aby otrzymywać powiadomienia.',
    currency: 'Waluta',
    currencyDesc: 'Ustaw preferowaną walutę',
    language: 'Język',
    languageDesc: 'Ustaw preferowany język.',
    rank: 'Rank',
    index: 'Indeks',
    farmer: 'Rolnik',
    date: 'Data',
    amount: 'Kwota',
    id: 'ID',
    appearance: 'Wygląd',
    appearanceDesc: 'Jasny, Ciemny',
    general: 'Ogólne',
    notifications: 'Powiadomienia',
    notificationsDesc: 'Części, Wypłaty',
    notification: 'Powiadomienia',
    notificationDesc: 'Wygrane bloki',
    home: 'Dom',
    news: 'Wiadomości',
    stats: 'Statystyki',
    blocksFound: 'Znalezione bloki',
    darkMode: 'Tryb ciemny',
    verifyFarm: 'Zweryfikuj farmę',
    settings: 'Ustawienia',
    charts: 'Charts',
    farms: 'Gospodarstwa',
    farmerName: 'Nazwa',
    farmerSettings: 'Ustawienia gospodarstwa',
    displayName: 'Nazwa wyświetlana',
    farmName: 'Nazwa aktualizacji',
    totalChiaAccumulated: 'Razem wypłacone',
    noPayoutsRecieved: 'Nie otrzymano jeszcze żadnych wypłat. Pociągnij w dół, aby odświeżyć.',
    overView: 'Przegląd',
    height: 'Wysokość',
    post: 'Post',
    giveaway: 'Giveaway',
    drawDate: 'Draw Date',
    ticketIssuance: 'TICKETS ISSUANCE',
    ticketsIssued: 'TICKETS ISSUED',
    giveawayEveryone:
      'All farmers participating in our pool are automatically eligible in our giveaway!',
    giveawayEveryday:
      'Every day farmers will be issued tickets based on their estimated farm size.',
    ticketDrawing:
      'Draw of the ticket number will happen live in our YouTube channel and done using Google random number generator. The winner will be the farmer with the ticket closest to the number draw. If two farmers are within the same range another number will be drawed until there is only one winner.',
    ticketAvailabilty: 'All tickets issued are made available in each farmer detail page.',
    ticketNumber: 'Ticket Number',
    tickets: 'Tickets',
    ticketsCalculator: 'Tickets Calculator',
    winners: 'Winners',
    prize: 'Prize',
    issuedTickets: 'Issued Tickets',
    winner: 'Winner',
    chiaPriceChart: 'Chia Price Chart',
  },
};
