export default {
  translation: {
    languageSelector: 'Seleccione a sua língua',
    welcome: 'Bem-vindo ao OpenChia.io Official Pool Protocol',
    trust: 'Uma piscina em que se pode confiar',
    open: 'Todo o nosso software é de código aberto',
    join: 'Junte-se ao nosso pool',
    chat: 'Converse connosco',
    fee: '1% de taxa',
    minPayout: 'Sem pagamento mínimo',
    instantPayout: 'Pagamento instantâneo',
    transparent: 'Transparente',
    feeDesc: 'Taxa baixa com opção de referência',
    minPayoutDesc: 'Porquê esperar para receber as suas recompensas?',
    instantPayoutDesc: 'Receba a sua recompensa o mais depressa possível',
    transparentDesc: 'Não temos nada a esconder. Explorador completo e troncos vivos',
    chiaPrice: 'Preço Chia',
    poolSpace: 'Espaço de piscina',
    etw: 'etw',
    blocks: 'Blocos',
    farmers: 'Agricultores',
    netspace: 'Netspace',
    currentEffort: 'Esforço actual',
    effort: 'Esforço',
    sinceLastWin: 'Desde a última vitória',
    rewards: 'Recompensas',
    profitability: 'Lucratividade',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 Horas',
    All: 'Todos',
    friendlyName: 'Nome Amigável',
    difficulty: 'Dificuldade',
    joinedAt: 'Join Join At',
    estimatedDailyEarnings: 'Esimated Daily Earnings',
    points: 'Pontos',
    utilizationSpace: 'Espaço de utilização',
    estimatedSize: 'Espaço delimitado',
    partials: 'Parciais',
    partial: 'parcial',
    successfulPartials: 'Parciais bem sucedidos',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Desempenho Parcial',
    harvesterCount: 'Os ceifeiros contam',
    farmerDetails: 'Detalhes do Agricultor',
    payouts: 'Pagamentos',
    farmedBlocks: 'Blocos de Agricultura',
    scanDesc: 'Digitalize o código QR a partir do link de login do pool para receber notificações',
    currency: 'Moeda',
    currencyDesc: 'Definir a moeda preferida',
    language: 'Língua',
    languageDesc: 'Definir língua preferida',
    rank: 'Rank',
    index: 'Índice',
    farmer: 'Agricultor',
    date: 'Data',
    amount: 'Montante',
    id: 'ID',
    appearance: 'Aparência',
    appearanceDesc: 'Luz, Escuridão',
    general: 'Geral',
    notifications: 'Notificações',
    notificationsDesc: 'Parciais, Pagamentos',
    notification: 'Notificação',
    notificationDesc: 'Blocos Ganhados',
    home: 'Casa',
    news: 'Notícias',
    stats: 'Estatísticas',
    blocksFound: 'Blocos encontrados',
    verifyFarm: 'Verify Farm',
    settings: 'Definições',
    charts: 'Gráficos',
    farms: 'Quintas',
    farmerName: 'Nome',
    farmerSettings: 'Farmer Settings',
    displayName: 'Nome de exibição',
    farmName: 'Nome de actualização',
    totalChiaAccumulated: 'Total Pago',
    noPayoutsRecieved:
      'Ainda não foram recebidos quaisquer pagamentos. Puxe para baixo para refrescar',
    overView: 'Resumo',
    height: 'Altura',
    post: 'Correio',
    giveaway: 'Giveaway',
    drawDate: 'Data do sorteio',
    ticketIssuance: 'EMISSÃO DE BILHETES',
    ticketsIssued: 'BILHETES EMITIDOS',
    giveawayEveryone:
      'Todos os agricultores que participam na nossa reserva são automaticamente elegíveis no nosso donativo!',
    giveawayEveryday:
      'Todos os dias serão emitidos bilhetes para os agricultores com base na sua estimativa da dimensão da exploração agrícola.',
    ticketDrawing:
      'O sorteio do número do bilhete será realizado em directo no nosso canal YouTube e feito utilizando o gerador de números aleatórios do Google. O vencedor será o agricultor com o bilhete mais próximo do número do sorteio. Se dois agricultores estiverem dentro do mesmo intervalo, outro número será sorteado até haver apenas um vencedor.',
    ticketAvailabilty:
      'Todos os bilhetes emitidos são disponibilizados na página de detalhe de cada agricultor.',
    ticketNumber: 'Número do bilhete',
    tickets: 'Bilhetes',
    ticketsCalculator: 'Calculadora de bilhetes',
    winners: 'Vencedores',
    prize: 'Prémio',
    issuedTickets: 'Bilhetes emitidos',
    winner: 'Vencedor',
    chiaPriceChart: 'Tabela de Preços Chia',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'Sem Parciais Aprovados por 1h',
    farmerBlockNotification: 'Bloco Ganho pelo Agricultor',
    farmerNotifications: 'Notificações agrícolas',
    groupName: 'Group Title',
  },
};
