export default {
  translation: {
    languageSelector: 'Выберите язык',
    welcome: 'Добро пожаловать на OpenChia.io Официальный протокол пула',
    trust: 'Пул, которому можно доверять.',
    open: 'Все наше программное обеспечение с открытым исходным кодом',
    join: 'Присоединяйтесь к нашему пулу',
    chat: 'Общайтесь с нами',
    fee: '1% комиссии',
    minPayout: 'Без минимальных выплат',
    instantPayout: 'Мгновенная выплата',
    transparent: 'Прозрачный',
    feeDesc: 'Низкая комиссия с возможностью привлечения рефералов',
    minPayoutDesc: 'Зачем ждать, чтобы получить свое вознаграждение?',
    instantPayoutDesc: 'Получите свое вознаграждение как можно скорее',
    transparentDesc: 'Нам нечего скрывать. Полноценный проводник и живые журналы',
    chiaPrice: 'Цена Чиа',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Блоки',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Current Effort',
    effort: 'Effort',
    sinceLastWin: 'С момента последней победы',
    rewards: 'Rewards',
    profitability: 'Profitabilty',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 часа',
    All: 'Все',
    friendlyName: 'Friendly Name',
    difficulty: 'Difficulty',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Предполагаемый ежедневный заработок',
    points: 'Points',
    utilizationSpace: 'Utilization Space',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Успешные частицы',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Partial Performance',
    harvesterCount: 'Количество комбайнов',
    farmerDetails: 'Детали фермера',
    payouts: 'Выплаты',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Сканируйте QR-код со ссылки входа в бассейн для получения уведомлений.',
    currency: 'Валюта',
    currencyDesc: 'Установите предпочитаемую валюту',
    language: 'Язык',
    languageDesc: 'Установить предпочитаемый язык.',
    rank: 'Rank',
    index: 'Индекс',
    farmer: 'Фермер',
    date: 'Дата',
    amount: 'Сумма',
    id: 'ID',
    appearance: 'Внешний вид',
    appearanceDesc: 'Светлый, темный',
    general: 'Общие',
    notifications: 'Уведомления',
    notificationsDesc: 'Части, выплаты',
    notification: 'Уведомление',
    notificationDesc: 'Выигранные блоки',
    home: 'Главная',
    news: 'Новости',
    stats: 'Статистика',
    blocksFound: 'Blocks Found',
    darkMode: 'Темный режим',
    verifyFarm: 'Verify Farm',
    settings: 'Настройки',
    charts: 'Графики',
    farms: 'Farms',
    farmerName: 'Name',
    farmerSettings: 'Настройки фермера',
    displayName: 'Display Name',
    farmName: 'Update Name',
    totalChiaAccumulated: 'Всего выплачено',
    noPayoutsRecieved: 'Выплаты еще не получены. Потяните вниз, чтобы обновить.',
    overView: 'Обзор',
    height: 'Высота',
    post: 'Post',
    giveaway: 'Giveaway',
    drawDate: 'Дата розыгрыша',
    ticketIssuance: 'ВЫДАЧА БИЛЕТОВ',
    ticketsIssued: 'TICKETS ISSUED',
    giveawayEveryone:
      'Все фермеры, участвующие в нашем пуле, автоматически получают право на участие в розыгрыше!',
    giveawayEveryday:
      'Каждый день фермерам будут выдаваться билеты в зависимости от предполагаемого размера их фермы.',
    ticketDrawing:
      'Розыгрыш номера билета будет проходить в прямом эфире на нашем YouTube-канале с использованием генератора случайных чисел Google. Победителем станет фермер с билетом, ближайшим к номеру, выпавшему в результате розыгрыша. Если два фермера окажутся в одном диапазоне, будет разыгран еще один номер, пока не останется только один победитель.',
    ticketAvailabilty:
      'Все выданные билеты доступны на странице подробной информации о каждом фермере.',
    ticketNumber: 'Номер билета',
    tickets: 'Tickets',
    ticketsCalculator: 'Калькулятор билетов',
    winners: 'Победители',
    prize: 'Приз',
    issuedTickets: 'Выданные билеты',
    winner: 'Победитель',
    chiaPriceChart: 'График цен на чиа',
    farmerOffline: 'Offline',
    farmerOfflineNotification: 'В течение 1 часа частицы не передавались',
    farmerBlockNotification: 'Блок, выигранный фермером',
    farmerNotifications: 'Уведомления о ферме',
  },
};
