export default {
  translation: {
    languageSelector: 'Выберите язык',
    welcome: 'Добро пожаловать на OpenChia.io Официальный протокол пула',
    trust: 'Пул, которому можно доверять.',
    open: 'Все наше программное обеспечение с открытым исходным кодом',
    join: 'Присоединяйтесь к нашему пулу',
    chat: 'Общайтесь с нами',
    fee: '1% комиссии',
    minPayout: 'Без минимальных выплат',
    instantPayout: 'Мгновенная выплата',
    transparent: 'Прозрачный',
    feeDesc: 'Низкая комиссия с возможностью привлечения рефералов',
    minPayoutDesc: 'Зачем ждать, чтобы получить свое вознаграждение?',
    instantPayoutDesc: 'Получите свое вознаграждение как можно скорее',
    transparentDesc: 'Нам нечего скрывать. Полноценный проводник и живые журналы',
    chiaPrice: 'Цена Чиа',
    poolSpace: 'Pool Space',
    etw: 'etw',
    blocks: 'Блоки',
    farmers: 'Farmers',
    netspace: 'Netspace',
    currentEffort: 'Current Effort',
    effort: 'Effort',
    sinceLastWin: 'С момента последней победы',
    rewards: 'Rewards',
    profitability: 'Profitabilty',
    '4h': '4h',
    '6h': '6h',
    '8h': '8h',
    '12h': '12h',
    '24h': '24h',
    '2d': '2d',
    '3d': '3d',
    '7d': '7d',
    '30d': '30d',
    '90d': '90d',
    '24Hours': '24 часа',
    All: 'Все',
    friendlyName: 'Friendly Name',
    difficulty: 'Difficulty',
    joinedAt: 'Joined At',
    estimatedDailyEarnings: 'Предполагаемый ежедневный заработок',
    points: 'Points',
    utilizationSpace: 'Utilization Space',
    estimatedSize: 'Esimated Space',
    partials: 'Partials',
    partial: 'partial',
    successfulPartials: 'Успешные частицы',
    failedPartials: 'Failed Partials',
    partialPerfomance: 'Partial Performance',
    harvesterCount: 'Количество комбайнов',
    farmerDetails: 'Детали фермера',
    payouts: 'Выплаты',
    farmedBlocks: 'Farmed Blocks',
    scanDesc: 'Сканируйте QR-код со ссылки входа в бассейн для получения уведомлений.',
    currency: 'Валюта',
    currencyDesc: 'Установите предпочитаемую валюту',
    language: 'Язык',
    languageDesc: 'Установить предпочитаемый язык.',
    rank: 'Rank',
    index: 'Индекс',
    farmer: 'Фермер',
    date: 'Дата',
    amount: 'Сумма',
    id: 'ID',
    appearance: 'Внешний вид',
    appearanceDesc: 'Светлый, темный',
    general: 'Общие',
    notifications: 'Уведомления',
    notificationsDesc: 'Части, выплаты',
    notification: 'Уведомление',
    notificationDesc: 'Выигранные блоки',
    home: 'Главная',
    news: 'Новости',
    stats: 'Статистика',
    blocksFound: 'Blocks Found',
    darkMode: 'Темный режим',
    verifyFarm: 'Verify Farm',
    settings: 'Настройки',
    charts: 'Графики',
    farms: 'Farms',
    farmerName: 'Name',
    farmerSettings: 'Настройки фермера',
    displayName: 'Display Name',
    farmName: 'Update Name',
    totalChiaAccumulated: 'Всего выплачено',
    noPayoutsRecieved: 'Выплаты еще не получены. Потяните вниз, чтобы обновить.',
    overView: 'Обзор',
  },
};
